plugins:
- jekyll-remote-theme

remote_theme: pmarsceill/just-the-docs
color_scheme: dark

aux_links_new_tab: true
aux_links:
  "GitHub":
  - {{ site.github.project_url }}
  
  License:
  - LICENSE.txt
  
  Notice:
  - NOTICE.txt
  
  "USD Releases":
    - "https://github.com/PixarAnimationStudios/USD/releases"

readme_index:
  enabled: true