name: CI
on: [push]

jobs:
  aswf-build:
    name: ASWF container
    runs-on: ubuntu-latest
    container:
      image: aswf/ci-usd:${{ matrix.year }}
      volumes:
      - ${{ github.workspace }}/tmp/katana:${{ github.workspace }}/tmp/katana
      - ${{ github.workspace }}/tmp/usd:${{ github.workspace }}/tmp/usd
      - ${{ github.workspace }}/build:${{ github.workspace }}/build

    strategy:
      fail-fast: false
      matrix:
        usd: ["19.11", "20.08"]
        year: [2019, 2020]
        katana: ["3.1v7", "3.6v2"]

    steps:

    # Install Katana
    - uses: j0yu/setup-rez@v1
    - uses: actions/checkout@v2
      with:
        repository: j0yu/rez-katana
        path: tmp/katana

    - run: rez build --install --variant 0
      working-directory: tmp/katana

    - name: Export KATANA_API_LOCATION
      run: rez env katana -c 'echo "::set-env name=KATANA_API_LOCATION::$REZ_KATANA_ROOT"'

    # Fetch USD
    - uses: actions/checkout@v2
      with:
        repository: PixarAnimationStudios/USD
        path: tmp/usd
        ref: v${{ matrix.usd }}

    # Build
    - uses: actions/checkout@v2
    - run: mkdir build dist
    - name: cmake generate
      working-directory: build
      run: >
        cmake ..
        -DKATANA_API_LOCATION=$KATANA_API_LOCATION
        -DUSD_ROOT=${{ github.workspace }}/dist
        -DPXR_PY_PACKAGE_NAME=fnpxr
        -DUSE_KATANA_THIRDPARTY_LIBS=ON
        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/dist
        -DUSE_KATANA_THIRDPARTY_LIBS=ON

    - working-directory: build
      run: cmake --build . --target install
