name: CI
on: [push]

jobs:
  aswf-build:
    name: ASWF container
    runs-on: ubuntu-latest
    container:
      image: aswf/ci-usd:2019
      volumes:
      - ${{ github.workspace }}/tmp/katana:${{ github.workspace }}/tmp/katana
      - ${{ github.workspace }}/tmp/usd:${{ github.workspace }}/tmp/usd
      - ${{ github.workspace }}/build:${{ github.workspace }}/build

    strategy:
      fail-fast: false
      matrix:
        usd: ["19.11", "20.08"]
        katana: ["3.1v7", "3.6v2"]

    steps:

    - name: Install Katana
      env:
        INSTALL_PATH: ${{ runner.temp }}/katana
      run: |
        set -x
        mkdir -p "$INSTALL_PATH"
        curl -sSL "http://thefoundry.s3.amazonaws.com/products/katana/releases/${{matrix.katana}}/Katana${{matrix.katana}}-linux-x86-release-64.tgz" \
        | tar -xzO "katana_files.tar.gz" \
        | tar -xz -C "$INSTALL_PATH"
        echo "::set-env name=KATANA_API_LOCATION::$REZ_BUILD_INSTALL_PATH"

    # Install Katana
    # - uses: actions/checkout@v2
    #   with:
    #     repository: j0yu/rez-katana
    #     path: tmp/katana

    # - name: Install Katana
    #   working-directory: tmp/katana
    #   env:
    #     RELEASES_URL: "http://thefoundry.s3.amazonaws.com/products/katana/releases"
    #     REZ_BUILD_INSTALL: 1
    #     REZ_BUILD_INSTALL_PATH: ${{ runner.temp }}/katana
    #     REZ_BUILD_SOURCE_PATH: ${{ github.workspace }}/tmp/katana
    #     REZ_PLATFORM_VERSION: linux
    #     REZ_ARCH_VERSION: x86_64

    #   run: |
    #     mkdir -p "$REZ_BUILD_INSTALL_PATH"
    #     bash -x linux.bash "${{ matrix.katana }}"
    #     echo "::set-env name=KATANA_API_LOCATION::$REZ_BUILD_INSTALL_PATH"
 
    # Fetch USD
    - uses: actions/checkout@v2
      with:
        repository: PixarAnimationStudios/USD
        path: tmp/usd
        ref: v${{ matrix.usd }}

    # Build
    - uses: actions/checkout@v2
    - run: mkdir build dist
    - name: cmake generate
      working-directory: build
      run: >
        cmake ..
        -DKATANA_API_LOCATION=$KATANA_API_LOCATION
        -DUSD_ROOT=${{ github.workspace }}/dist
        -DPXR_PY_PACKAGE_NAME=fnpxr
        -DUSE_KATANA_THIRDPARTY_LIBS=ON
        -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/dist
        -DUSE_KATANA_THIRDPARTY_LIBS=ON

    - working-directory: build
      run: cmake --build . --target install
